account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'authentication'

from . import views

urlpatterns = [
    #path('me/', LoginView.as_view(), name='login'),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from rest_framework_simplejwt.views import TokenObtainPairView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('rest_framework.urls')),
    path('api/', include('authentication.api.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/', include('empresa.api.v1.urls')),
    path('api/v2/', include('empresa.api.v2.urls')),
]

estoque/forms.py
from django import forms

from .models import Empresa, Product, Inventory, Order
from django.forms import inlineformset_factory


class EmpresaModelForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = ['name', 'email', 'type']

class ProdutModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'tipo', 'fabricatedAt']
    
class EstoqueModelForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = ['quantity', 'product']

class OrderModelForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['quantity']
        

estoque/templates/estoque/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Controll</title>

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header>
        <div class="empresa-info">
            <h1 id="title" >Logo</h1>
            <ul>   
                <a href="#"><li>Início</li></a>
                <a href="#"><li>Sobre</li></a>
                <a href="#"><li>Contato</li></a>
           </ul>
        </div>
        <ul>   
            {% if user.empresa %}
            <a href="{% url 'estoque:empresa' %}"><li> Minha Empresa</li></a>
            <a href="#"><li> # {{user.username}}</li></a>
            <a href="{% url 'authentication:logout' %}"><li> Logout </li></a>
            {% endif %}
        </ul>
    </header>
    <nav>
        <ul>
            <a href="{% url 'estoque:empresa' %}"><li>Empresa</li></a>
            <a href="{%  url 'estoque:estoques' %}"><li>Inventário</li></a>
            <a href="{%  url 'estoque:registros' %}"><li>Registros</li></a>
        </ul>
    </nav>
    <main>
        <div>
            {% block title %}{% endblock title %}
        </div>
           
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
    <footer>made by @jaquiso_</footer>
</body>
</html>

estoque/templates/estoque/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <link rel="stylesheet" href="{% static 'css/media.css'%}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bai+Jamjuree:wght@300;400&family=Montserrat&family=Open+Sans:wght@300;400&family=Roboto&display=swap" rel="stylesheet">

    <title>Controll</title>
</head>
<body>
    <header>
        <div class="empresa-info">
            <h1 id="title" >Logo</h1>
            <ul>   
                <a href="#"><li>Início</li></a>
                <a href="#"><li>Sobre</li></a>
                <a href="#"><li>Contato</li></a>
           </ul>
        </div>
        <ul>   
            {% if not user.is_authenticated %}
            <a href="{% url 'authentication:login' %}"><li>Login</li></a>
            <a href="{% url 'authentication:register' %}" id="iniciar-controle-btn"><li>Crie sua conta</li></a>
            {% else %}
            {% if user.empresa %}
            <a href="{% url 'estoque:empresa' %}"><li> Minha Empresa</li></a>
            {% endif %}
            <a href="#"><li> # {{user.username}}</li></a>
            <a href="{% url 'authentication:logout' %}"><li> Logout </li></a>
            {% endif %}
        </ul>
    </header>
    <main>
        {{errors}}
        <aside>
            <span>
                <h2>Iniciar Controle</h2>
            </span>
            <h2>Da sua Empresa</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            
            <form action="{% url 'estoque:new_empresa' %}" method="post">
                {% csrf_token %}

                <input name="name" type="text" placeholder="Nome da empresa" />
                <input name="email" type="email" placeholder="Email" />
                
                
                <p>Selecione o tipo da sua empresa:</p>
                <div class="radios">
                    <div>
                        <input checked type="radio" name="type" value="market" />
                        <label for="">Mercado</label>
                    </div>
                    <div>
                        <input type="radio"  name="type" value="other"/>
                        <label for="">Outro</label>
                    </div>
                </div>
  
                <input type="submit" value="iniciar" />
            </form>
        </aside>

        <article>
            <img id="image" src="{% static 'images/image.png' '%}" alt="controller" width="590" height="483" > 
        </article>
    </main>
</body>
</html>